trigger:
  branches:
    include:
      - refs/tags/release-bindings-v*

pr: none

pool:
  vmImage: 'macOS-13'

variables:
  - group: nuget.org

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- bash: |
    echo "##vso[build.updatebuildnumber]pullrequests-tonestro-maui-facebookslim-android-$(Build.SourceBranchName)-$(Build.BuildId)"
  displayName: Set Build Number

- bash: |
    sudo dotnet workload restore
  displayName: Restore Workloads

- bash: |
    cd java/facebookslim
    ./gradlew build
    cd ../..
  displayName: Gradle Build

- bash: |
    cd Tonestro.Maui.FacebookSlim.Droid
    dotnet build -c Release
    dotnet pack -c Release
    cd ..
  displayName: Build and Pack

- bash: |
    cd Tonestro.Maui.FacebookSlim.Droid/nugetoutput
    numberOfNugetFiles=$(ls *.nupkg | wc -l)
    if [[ numberOfNugetFiles -ne 1 ]]; then
      echo "WRONG NUMBER OF NUGET FILES: ${numberOfNugetFiles}"
      exit 1
    fi
    eval $(stat -s *.nupkg)
    if [[ $st_size -lt 1500000 ]]; then
      echo "NUGET FILE TOO SMALL: ${st_size}"
      exit 1
    else
      echo "NUGET SIZE: ${st_size}"
    fi
    cd ../..
  displayName: Check nuget file

- task: PublishBuildArtifacts@1
  displayName: publish nugetoutput
  inputs:
    PathtoPublish: 'Tonestro.Maui.FacebookSlim.Droid/nugetoutput'
    ArtifactName: 'nugetoutput'
    publishLocation: 'Container'
    StoreAsTar: true

- bash: |
    dotnet nuget push Tonestro.Maui.FacebookSlim.Droid/nugetoutput/Tonestro.Maui.FacebookSlim.Droid.*.nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Tonestro.Maui.FacebookSlim.Droid'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceBranchName)'
    title: 'Tonestro.Maui.FacebookSlim.Droid $(bindingsVersion)'
    assets: 'Tonestro.Maui.FacebookSlim.Droid/nugetoutput/Tonestro.Maui.FacebookSlim.Droid.*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
